server {
    server_name *.pengeflyt.com;
    return 301 https://$host$request_uri;


    listen 127.0.0.1:8443 ssl proxy_protocol; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/pengeflyt.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pengeflyt.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {

    listen 127.0.0.1:8443 ssl proxy_protocol;

    server_name pengeflyt.com www.pengeflyt.com api.pengeflyt.com rp.pengeflyt.com;
    ssl_certificate /etc/letsencrypt/live/pengeflyt.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pengeflyt.com/privkey.pem; # managed by Certbot

    include snippets/errors.conf;

    location = /ssh/cashflow {
        client_max_body_size 1k;
        content_by_lua_file /usr/local/openresty/nginx/lua/ssh-websocket.lua;
    }

    location / {
        proxy_pass http://10.119.85.50;
        include snippets/proxy-headers.conf;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name pengeflyt.com www.pengeflyt.com api.pengeflyt.com rp.pengeflyt.com;

    location ^~ /.well-known/acme-challenge/ {
        root /etc/letsencrypt/webroot;
        default_type text/plain;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
