server {
    server_name *.pengeflyt.com;
    return 301 https://$host$request_uri;

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/pengeflyt.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pengeflyt.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name pengeflyt.com www.pengeflyt.com api.pengeflyt.com rp.pengeflyt.com;
    ssl_certificate /etc/letsencrypt/live/pengeflyt.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pengeflyt.com/privkey.pem; # managed by Certbot

    include snippets/errors.conf;

    location / {
        proxy_pass http://localhost:10001;
        include snippets/proxy-headers.conf;
    }
}

server {
    if ($host = rp.pengeflyt.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = api.pengeflyt.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = www.pengeflyt.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    listen [::]:80;

    server_name *.pengeflyt.com;
    return 404; # managed by Certbot
}
