services:
  mc-router:
    image: itzg/mc-router:1.47.1@sha256:177433dd91507339924d60205a19ae9a289afd0e69dbad54e1a55d497f7523f8
    container_name: minecraft-router
    restart: unless-stopped
    ports:
      - "127.0.0.1:25566:25565"
    environment:
      RECEIVE_PROXY_PROTOCOL: "true"
      CONNECTION_RATE_LIMIT: "20"
      MAPPING: |
        name-pending.hanasand.com=name_pending_server:25565
        67.hanasand.com=create-server:25565
        cobbleverse.hanasand.com=cobbleverse:25565
    networks:
      - name-pending
      - create
      - cobbleverse
    mem_limit: 128m
    cpus: "0.5"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  name-pending:
    external: true
    name: name_pending_server_default
  create:
    external: true
    name: 67_default
  cobbleverse:
    external: true
    name: cobbleverse_default
