error_page 400 /errors/render?code=400;
error_page 401 /errors/render?code=401;
error_page 403 /errors/render?code=403;
error_page 404 /errors/render?code=404;
error_page 405 /errors/render?code=405;
error_page 406 /errors/render?code=406;
error_page 408 /errors/render?code=408;
error_page 409 /errors/render?code=409;
error_page 410 /errors/render?code=410;
error_page 418 /errors/render?code=418;
error_page 429 /errors/render?code=429;
error_page 451 /errors/render?code=451;
error_page 500 /errors/render?code=500;
error_page 501 /errors/render?code=501;
error_page 502 /errors/render?code=502;
error_page 503 /errors/render?code=503;
error_page 504 /errors/render?code=504;

location = /errors/render {
    internal;
    content_by_lua_file /usr/local/openresty/nginx/lua/error_page.lua;
}
